import { Fira_Sans as FireSans, Merienda } from 'next/font/google'
import Header from '@/components/header'
import type { Metadata } from 'next'
import clsx from 'clsx'
import './globals.css'

const firaSans = FireSans({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-open-sans',
})

const merienda = Merienda({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-merienda',
})

export const metadata: Metadata = {
  title: 'Portfolio - Iarlen Reis',
  description: 'Generated by create next app',
  keywords: [
    'Iarlen Reis',
    'Desenvolvedor Front-end',
    'JavaScript',
    'React',
    'Next.js',
    'Portfolio',
    'TypeScript',
    'Tailwind',
    'React Native',
    'Java',
    'HTML',
  ],
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body className={clsx(firaSans.className, merienda.variable)}>
        <Header />
        <main className="container mx-auto px-3">{children}</main>
      </body>
    </html>
  )
}
